### ISSUE TITLE
ReasonReference pointing to CancerConditionParent

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/fsh-mcode#109]
In `CancerRelatedSurgicalProcedure` and `CancerRelatedRadiationProcedure`, the `ReasonReference` element is pointing to `CancerConditionParent`.

In the IG, this profile is described as an abstract class (should it even be there?). Why not point directly to `PrimaryCancerCondition` and `SecondaryCancerCondition` as choices?

**Comment by markkramerus** [comment]
This in intentional and allows further specialization of mCODE for CodeX and other derived IGs. If we limit to Primary and Secondary Cancer Condition, it is a closed set. In previous versions, we also included Tumor. Using the current approach, we can add tumor later as a child of CancerConditionParent.
