### ISSUE TITLE
Change ^status to #active on all Profiles and Extensions

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#53]
Ugh. Chris might be changing the default status of all StructureDefinitions to #draft in the next version of SUSHI. We want our SDs to be #active, across the board. 
FYI, here are the definitions of the codes #active, #draft, #unknown: http://hl7.org/fhir/R4/valueset-publication-status.html

**Comment by cmoesel** [comment]
Making default status `#draft` was an effort to align w/ the default state that Forge uses -- and an assumption that when most people start authoring profiles/extensions, they'll be draft at that point.  Profiles/extensions being authored in an already active state seems like an exception to the rule rather than the rule itself.

**Comment by cmoesel** [comment]
But yeah, whether we change the default back to `#active` or not, `#active` seems appropriate for the profiles/extensions in the mCODE 1.0.0 release.

**Comment by CarolinePotteiger** [comment]
All the mCODE StructureDefinitions have a status of #active.
