### ISSUE TITLE
Whitespace warning from IG Pub

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#56]
StructureDefinition/CancerGeneticVariant: StructureDefinition.snapshot.element[43].mapping[3].map	warning	value should not start or finish with whitespace

StructureDefinition/GenomicRegionStudied: StructureDefinition.snapshot.element[16].mapping[3].map | warning | value should not start or finish with whitespace

**Comment by markkramerus** [comment]
I've tried to track this down, but failed. Need some new inspiration. It _might_ be inherited from US Core (and not under our control), but its not on their QA page.

**Comment by cmoesel** [comment]
This feels like a bug in the mappings defined in the parent SD we're inheriting from.  In theory, we can fix this in SUSHI when we pull down the parent SD.  Although technically it should create a diff, I don't feel too back making this technical fix without forcing a diff.  Let me know if we should do this and the general priority.  The workaround would be to use escape syntax to overwrite the mapping w/ a valid value (but would also cause a diff).

**Comment by markkramerus** [comment]
Maybe.

**Comment by cmoesel** [comment]
This actually brings up something I was considering earlier this week -- if SUSHI should export _only_ the differentials (and not the snapshot).  If we do this, then the IG Publisher reconstructs the snapshot from the differentials and we _shouldn't_ get dinged by errors in the original snapshot.

I actually experimented with this a few days ago and it _mostly_ worked, but it actually choked on a few slicings and I couldn't figure out why (they _seemed_ valid).  I put it aside because it seemed a significant change to make right now and I thought we'd probably need help from the FHIR community to nail down those issues reconstructing the snapshot.

**Comment by mlterryMitre-zz** [comment]
@markkramerus - what do you want to do about this? Seems like we're blocked for now.

**Comment by markkramerus** [comment]
We are no longer getting this error. Probably a fix from the IG Pub or template side of the house. Closing
